"""NEKTE Protocol SDK — Token-efficient agent-to-agent coordination."""

from nekte.domain.types import (
    AgentCard,
    Capability,
    CapabilityRef,
    CapabilitySchema,
    CapabilitySummary,
    ContextCompression,
    ContextEnvelope,
    ContextPermissions,
    DetailLevel,
    DiscoveryLevel,
    InvokeResult,
    MultiLevelResult,
    NekteError,
    NekteMethod,
    NekteRequest,
    NekteResponse,
    Task,
    TaskResult,
    TaskStatus,
    TokenBudget,
)
from nekte.domain.errors import NekteProtocolError, NEKTE_ERRORS
from nekte.domain.hash import compute_version_hash, verify_version_hash, compute_content_hash
from nekte.domain.budget import estimate_tokens, resolve_budget, create_budget, DEFAULT_BUDGETS
from nekte.domain.task import (
    TaskEntry,
    TaskTransitionError,
    TASK_TRANSITIONS,
    CANCELLABLE_STATES,
    RESUMABLE_STATES,
    TERMINAL_STATES,
    is_valid_transition,
    is_terminal,
    is_active,
    is_cancellable,
    is_resumable,
    create_task_entry,
    transition_task,
    save_checkpoint,
)
from nekte.domain.sse import (
    SseEvent,
    SseProgressEvent,
    SsePartialEvent,
    SseCompleteEvent,
    SseErrorEvent,
    SseCancelledEvent,
    SseSuspendedEvent,
    SseResumedEvent,
    encode_sse_event,
    parse_sse_event,
    parse_sse_stream,
)

NEKTE_VERSION = "0.3.0"
WELL_KNOWN_PATH = "/.well-known/nekte.json"

__all__ = [
    "NEKTE_VERSION",
    "WELL_KNOWN_PATH",
    # Types
    "DetailLevel",
    "DiscoveryLevel",
    "TokenBudget",
    "CapabilityRef",
    "CapabilitySummary",
    "CapabilitySchema",
    "Capability",
    "AgentCard",
    "ContextCompression",
    "ContextPermissions",
    "ContextEnvelope",
    "MultiLevelResult",
    "InvokeResult",
    "Task",
    "TaskStatus",
    "TaskResult",
    "NekteMethod",
    "NekteRequest",
    "NekteResponse",
    "NekteError",
    # Errors
    "NekteProtocolError",
    "NEKTE_ERRORS",
    # Hash
    "compute_version_hash",
    "verify_version_hash",
    "compute_content_hash",
    # Budget
    "estimate_tokens",
    "resolve_budget",
    "create_budget",
    "DEFAULT_BUDGETS",
    # Task
    "TaskEntry",
    "TaskTransitionError",
    "TASK_TRANSITIONS",
    "CANCELLABLE_STATES",
    "RESUMABLE_STATES",
    "TERMINAL_STATES",
    "is_valid_transition",
    "is_terminal",
    "is_active",
    "is_cancellable",
    "is_resumable",
    "create_task_entry",
    "transition_task",
    "save_checkpoint",
    # SSE
    "SseEvent",
    "SseProgressEvent",
    "SsePartialEvent",
    "SseCompleteEvent",
    "SseErrorEvent",
    "SseCancelledEvent",
    "SseSuspendedEvent",
    "SseResumedEvent",
    "encode_sse_event",
    "parse_sse_event",
    "parse_sse_stream",
]
