
export default new Map([
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/cache.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fcache.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/authentication.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fauthentication.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/progressive-discovery.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fprogressive-discovery.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/streaming-delegate.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fstreaming-delegate.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/grpc.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fgrpc.mdx&astroContentModuleFlag=true")],
["src/content/docs/architecture/layers.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Farchitecture%2Flayers.mdx&astroContentModuleFlag=true")],
["src/content/docs/architecture/overview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Farchitecture%2Foverview.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/mcp-bridge.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fmcp-bridge.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/zero-schema.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fzero-schema.mdx&astroContentModuleFlag=true")],
["src/content/docs/examples/mcp-migration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fexamples%2Fmcp-migration.mdx&astroContentModuleFlag=true")],
["src/content/docs/examples/two-agents.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fexamples%2Ftwo-agents.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/benchmarks.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fbenchmarks.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/typescript.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Ftypescript.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/agent-card.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Fagent-card.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/error-codes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Ferror-codes.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/overview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Foverview.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/primitives.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Fprimitives.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/task-lifecycle.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Ftask-lifecycle.mdx&astroContentModuleFlag=true")],
["src/content/docs/protocol/transports.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fprotocol%2Ftransports.mdx&astroContentModuleFlag=true")]]);
		